# Generated by Django 3.2.7 on 2021-09-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnvsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palindromecheck',
            name='IsPalindrome',
            field=models.BooleanField(default=False),
        ),
    ]
